"""dsg2 report generator — run from any directory, all paths are absolute."""

import subprocess
import re
from datetime import date
from fpdf import FPDF

REPO = "/Users/mehmetkucuk/Documents/GitHub/digi-soul"
OUT  = f"{REPO}/reports/dsg_report_2026-06-21.pdf"

def git(cmd):
    r = subprocess.run(["git", "-C", REPO] + cmd.split(), capture_output=True, text=True)
    return r.stdout.strip()

def clean(text):
    """Strip non-latin-1 characters so fpdf core fonts never crash."""
    return re.sub(r"[^\x00-\xFF]", "?", text)


# ── Gather git data ────────────────────────────────────────────────────────────

log_lines = git("log --oneline -10").splitlines()

commits = []
for line in log_lines:
    parts = line.split(" ", 1)
    if len(parts) == 2:
        sha, subject = parts
        date_str = git(f"show -s --format=%ad --date=short {sha}")
        author   = git(f"show -s --format=%an {sha}")
        body     = git(f"show -s --format=%b {sha}")
        stat     = git(f"show --stat --format= {sha}")
        commits.append({
            "sha": sha, "subject": subject, "date": date_str,
            "author": author, "body": body.strip(), "stat": stat.strip()
        })

known_gaps = [
    "blood_flow signal not yet consumed by brain, lungs, or liver (medium priority)",
    "No motor neurons for muscles or vasculature in circuit.py",
    "No autonomous pathogen injection — ImmuneSystem cannot be stress-tested",
    "adrenal_gland tachycardia handler is a stub (pass) — tachycardia detection unimplemented",
    "language_bridge.py exists but is not imported anywhere — possibly dead code",
    "SpacePhysiology and VascularSystem access bus._organs directly, bypassing bus API",
    "organ_agent_idea.txt roadmap file is missing from the repository",
    "Brain CLAUDE_MODEL set to haiku-4-5-20251001 — verify this ID is still valid",
]


# ── Build PDF ──────────────────────────────────────────────────────────────────

class PDF(FPDF):
    def header(self):
        self.set_font("Courier", "B", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 6, clean("digi-soul inc.  |  Development Report  |  2026-06-21"), align="C")
        self.ln(4)
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)

    def footer(self):
        self.set_y(-15)
        self.set_font("Courier", "I", 7)
        self.set_text_color(150, 150, 150)
        self.cell(0, 6, clean(f"digi-soul inc.  |  generated by dsg2  |  page {self.page_no()}"), align="C")

    def title_text(self, txt, size=14, color=(30, 30, 30)):
        self.set_font("Helvetica", "B", size)
        self.set_text_color(*color)
        self.cell(0, 10, clean(txt), ln=True)
        self.ln(1)

    def body_text(self, txt, size=9, color=(50, 50, 50)):
        self.set_font("Helvetica", "", size)
        self.set_text_color(*color)
        self.multi_cell(0, 5, clean(txt))
        self.ln(1)

    def section(self, title):
        self.ln(4)
        self.set_fill_color(240, 240, 245)
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(40, 40, 100)
        self.cell(0, 7, clean("  " + title), fill=True, ln=True)
        self.ln(2)


pdf = PDF()
pdf.set_auto_page_break(auto=True, margin=18)

# ── Page 1: Title ──────────────────────────────────────────────────────────────
pdf.add_page()
pdf.ln(20)
pdf.set_font("Helvetica", "B", 22)
pdf.set_text_color(20, 20, 80)
pdf.cell(0, 12, "digi-soul inc.", ln=True, align="C")
pdf.set_font("Helvetica", "", 14)
pdf.set_text_color(80, 80, 80)
pdf.cell(0, 8, "Development Report", ln=True, align="C")
pdf.ln(6)

pdf.set_draw_color(100, 100, 180)
pdf.set_line_width(0.5)
pdf.line(40, pdf.get_y(), 170, pdf.get_y())
pdf.ln(8)

info = [
    ("Date",       "2026-06-21"),
    ("Author",     "Mehmet Kucuk"),
    ("Repository", "github.com/MehmetKay-sudo/digi-soul"),
    ("Engineer",   "dsg (software engineering agent)"),
    ("Reporter",   "dsg2 (reporting agent)"),
    ("Manager",    "mdsg (manager agent)"),
]
for label, value in info:
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(42, 7, clean(label + ":"))
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 7, clean(value), ln=True)

pdf.ln(10)
pdf.set_font("Helvetica", "I", 9)
pdf.set_text_color(100, 100, 100)
pdf.multi_cell(0, 5, clean(
    "This report summarises engineering work carried out by the dsg agent on 2026-06-21, "
    "as instructed by Mehmet Kucuk. It covers two feature commits, the changes made, "
    "and the open issues remaining in the digi-soul humanoid brain/body simulator."
))

# ── Page 2: Commit summary table ──────────────────────────────────────────────
pdf.add_page()
pdf.section("Commit Summary")

col_w = [22, 26, 142]
headers = ["Hash", "Date", "Subject"]
pdf.set_font("Helvetica", "B", 9)
pdf.set_fill_color(220, 220, 235)
pdf.set_text_color(20, 20, 60)
for w, h in zip(col_w, headers):
    pdf.cell(w, 7, clean(h), border=1, fill=True)
pdf.ln()

pdf.set_font("Courier", "", 8)
fill = False
for c in commits:
    pdf.set_fill_color(248, 248, 252) if fill else pdf.set_fill_color(255, 255, 255)
    pdf.set_text_color(40, 40, 40)
    subj = clean(c["subject"])[:72] + ("..." if len(c["subject"]) > 72 else "")
    pdf.cell(col_w[0], 6, clean(c["sha"]), border=1, fill=True)
    pdf.cell(col_w[1], 6, clean(c["date"]), border=1, fill=True)
    pdf.cell(col_w[2], 6, subj, border=1, fill=True)
    pdf.ln()
    fill = not fill

# ── Per-commit detail ──────────────────────────────────────────────────────────
pdf.section("Per-Commit Detail")

for c in commits[:5]:  # top 5 commits
    pdf.set_font("Courier", "B", 9)
    pdf.set_text_color(20, 20, 80)
    pdf.cell(0, 6, clean(f"{c['sha']}  {c['date']}  —  {c['author']}"), ln=True)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 5, clean(c["subject"]), ln=True)
    if c["body"]:
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(70, 70, 70)
        pdf.multi_cell(0, 4, clean(c["body"]))
    if c["stat"]:
        pdf.set_font("Courier", "", 7)
        pdf.set_text_color(90, 90, 90)
        for stat_line in c["stat"].splitlines()[:12]:
            pdf.cell(0, 4, clean("  " + stat_line), ln=True)
    pdf.ln(4)
    pdf.set_draw_color(220, 220, 220)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)

# ── Open Issues ────────────────────────────────────────────────────────────────
pdf.add_page()
pdf.section("Open Issues / Known Gaps")

pdf.set_font("Helvetica", "", 9)
pdf.set_text_color(50, 50, 50)
for gap in known_gaps:
    pdf.cell(6, 5, clean("-"))
    pdf.multi_cell(0, 5, clean(gap))
    pdf.ln(1)

pdf.ln(4)
pdf.set_font("Helvetica", "I", 8)
pdf.set_text_color(120, 120, 120)
pdf.multi_cell(0, 4, clean(
    "Roadmap note: the organ_agent_idea.txt file (missing from repo) planned a migration "
    "from hardcoded organ if/elif logic to Claude tool-use agent loops. "
    "Recommended order: Brain -> Immune -> Adrenal -> Liver -> rest."
))

pdf.output(OUT)
print(f"Report written to: {OUT}")
